### ISSUE TITLE
Icons for categories

### ISSUE THREAD

**Issue by jtamiace** [learningequality/kolibri-ecosystem#20]
The new category taxonomy will have 3 hierarchy levels. We are providing iconography for the first 2 levels.

Example: School --> Mathematics --> Algebra
School and Mathematics will have icons, but Algebra will not.

Refer to the [taxonomy spreadsheet](https://docs.google.com/spreadsheets/d/16m_ELq6-hmBgveV3YJ6e_q0YmCRB0av2K22er_nEQuk/edit#gid=323352335) for the most up to date listing of categories, and the Figma file for drafts of the iconography selections.

**Comment by jtamiace** [comment]
WIP

https://www.figma.com/file/uiZuCIqh2KYvBUfbCiJyyA/Hybrid-Learning?node-id=1665%3A21

**Comment by indirectlylit** [comment]
some implications for icon design and management might come from discussions about internationalization and community-based evolution of the categories and organizational systems

**Comment by indirectlylit** [comment]
> internationalization and community-based evolution of the categories and organizational systems

On this point:

For 0.15 we decided to keep categorical systems standardized within Studio rather than allowing users to define their own category systems. While it would have been better to allow custom categories, having a centralized and well-defined set of categories made it much easier to design a set of icons and translate the terms.
